[flow] a bunch of actions.

diff --git a/bin/git-common b/bin/git-common
--- a/bin/git-common
+++ b/bin/git-common
@@ -157,6 +157,29 @@ git_is_clean_working_tree() {
 	return 0
 }
 
+#
+# git_fetch_branch()
+#
+# $1 Origin - Where to fetch from
+# $2 Branch - Which branch to fetch
+#
+# This fetches the given branch from the given origin.
+# Instead of storing it in FETCH_HEAD it will be stored in
+# refs/remotes/<origin>/<branch>
+#
+git_fetch(){
+  local origin branch
+  [ -n "$1" ] || die "No origin passed."
+  [ -n "$2" ] || die "No branch passed."
+  origin="$1"
+  branch="$2"
+  if git_remote_branch_exists "$origin/$branch"; then
+    git fetch -q "$origin" "$branch":refs/remotes/"$origin"/"$branch" || die "Could not fetch $branch from $origin."
+  else
+      die "Branch $origin/$branch not exists."
+  fi
+}
+
 git_checkout(){
   local branch current_branch
   [ -n "$1" ] || die "git_checkout: No branch name passed."
@@ -205,6 +228,21 @@ git_compare_refs() {
 	else
 		return 0
 	fi
+}
+
+#
+# git_is_branch_merged_into()
+#
+# Checks whether branch $1 is successfully merged into $2
+#
+git_is_branch_merged_into() {
+	local merge_hash base_hash
+
+	merge_hash=$(git merge-base "$1"^{} "$2"^{})
+	base_hash=$(git rev-parse "$1"^{})
+
+	# If the hashes are equal, the branches are merged.
+	[ "$merge_hash" = "$base_hash" ]
 }
 
 git_editor() {
diff --git a/bin/git-flow-feature b/bin/git-flow-feature
--- a/bin/git-flow-feature
+++ b/bin/git-flow-feature
@@ -2,21 +2,59 @@
 
 SUBDIRECTORY_OK="yes"
 
-source $(git stats --script-location $0)/git-common
+source $(git stats --script-location $0)/git-flow-common
 
 git_get flow.prefix.feature >/dev/null 2>&1 || die "Flow is not using feature branches. Use 'git flow init -f' to reconfigure."
 prefix=$(git_get flow.prefix.feature)
 
 parse_args(){
-  if empty "$1"; then
-    die "No branch candidate name passed."
-  else
-    candidate="$1"
+  case "$1" in
+    -h ) usage ;;
+    * ) NAME="$1"
+  esac
+
+  if ! empty "$NAME"; then
+    if startswith "$NAME" "$prefix"; then
+      NAME=${NAME##$prefix}
+    fi
+    BRANCH="$prefix$NAME"
   fi
-  candidate_branch="$prefix$candidate"
+}
+
+default(){
+  list "$@"
+}
+
+help(){
+USAGE='' && read -r -d '' USAGE <<'EOF'
+feature
+
+git flow feature [list]
+git flow feature start
+git flow feature finish
+git flow feature publish
+git flow feature track
+git flow feature diff
+git flow feature rebase
+git flow feature delete
+
+Manage your feature branches.
+
+For more specific help type the command followed by -h
+EOF
+  usage
 }
 
 list(){
+  USAGE="\
+feature [list] [-h] [-v]
+
+Lists all the existing feature branches in the local repository.
+
+    -h   Show help
+    -v   Verbose output
+"
+  parse_args "$@"
   local feature_branchs base develop_hash branch_hash
   feature_branchs=$(git_local_branches_with_prefix "$prefix")
   if empty $feature_branchs; then
@@ -54,6 +92,14 @@ list(){
 }
 
 start(){
+  USAGE="\
+git flow feature start [-h] [-F] <name> [<base>]
+
+Start new feature <name>, optionally basing it on <base> instead of <develop>
+    -h         Show help
+    --fetch    Fetch from origin before performing local operation
+"
+
   for arg do
     shift
     case "$arg" in
@@ -65,41 +111,59 @@ start(){
   base=${2:-$DEVELOP_BRANCH}
 
   require_local_branch "$base"
-  flow_set_branch_base $candidate_branch $base
+  ! empty "$NAME" || die "No branch name passed."
+  flow_set_branch_base $BRANCH $base
 
   if flag fetch; then
-    git_fetch_branch "$ORIGIN" "$base"
+    git_fetch "$ORIGIN" "$base"
   fi
 
-  require_branch_absent "$candidate_branch"
+  require_branch_absent "$BRANCH"
 
+  # If the origin branch counterpart exists, assert that the local branch
+	# isn't behind it (to avoid unnecessary rebasing)
   if git_remote_branch_exists "$ORIGIN/$base"; then
     require_branches_equal "$base" "$ORIGIN/$base"
   fi
 
-  git_checkout $candidate_branch $base;
-  note "Branch $candidate_branch created, based on $base."
-  note "You are in branch $(git stats --long-current-branch)"
+  git_checkout $BRANCH $base;
+  note "Branch $BRANCH created, based on $base."
+  note "You are in branch $(git stats --long-current-branch)."
+  note "Use 'git flow feature finish $NAME' when done."
 }
 
 finish(){
+  USAGE="\
+  git flow feature finish [-h] [-F] [-r] [-p] [-k] [-D] [-S] [--no-ff] <name|nameprefix>
+
+  Finish feature <name>
+      -h                Show this help
+      --fetch            Fetch from origin before performing finish
+      --rebase           Rebase before merging
+      --preserve-merges  Preserve merges while rebasing
+      --push               Push to origin after performing finish
+      --keep             Keep branch after performing finish
+      --squash           Squash feature during merge
+  "
   for arg do
     shift
     case "$arg" in
       --fetch) set_flag fetch; ;;
       --rebase) set_flag rebase; ;;
+      --preserve-merges) set_flag preservemerge ;;
+      --push) set_flag push ;;
       --keep) set_flag keep; ;;
       *) set -- "$@" "$arg"; ;;
     esac
   done
   parse_args "$@"
-  if empty "$candidate"; then
-    candidate=$(git stats --long-current-branch)
-    candidate_branch=$prefix$candidate
+  if empty "$NAME"; then
+    NAME=$(git stats --long-current-branch)
+    BRANCH=$NAME
   fi
-  require_branch_prefix "$candidate_branch" "$prefix"
-  require_branch "$candidate_branch"
-  base=$(flow_get_branch_base "$candidate_branch")
+  require_branch_prefix "$BRANCH" "$prefix"
+  require_branch "$BRANCH"
+  base=$(flow_get_branch_base "$BRANCH")
   base=${base:-$DEVELOP_BRANCH}
   require_local_branch "$base"
 
@@ -109,18 +173,18 @@ finish(){
   # We always fetch the Branch from Origin
 	# This is done to avoid possible commits on the remote that are not
 	# merged into the local branch
-	if git_remote_branch_exists "$ORIGIN/$candidate_branch"; then
-		git_fetch_branch "$ORIGIN" "$candidate_branch"
+	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+		git_fetch "$ORIGIN" "$BRANCH"
 	fi
 
   # Update local branches with remote branches
 	if flag fetch; then
-		git_fetch_branch "$ORIGIN" "$base"
+		git_fetch "$ORIGIN" "$base"
 	fi
 
   # Check if the local branches have all the commits from the remote branches
-	if git_remote_branch_exists "$ORIGIN/$candidate_branch"; then
-			require_branches_equal "$candidate_branch" "$ORIGIN/$candidate_branch"
+	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+			require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
 	fi
 	if git_remote_branch_exists "$ORIGIN/$base"; then
 		require_branches_equal "$base" "$ORIGIN/$base"
@@ -128,21 +192,25 @@ finish(){
 
   # If the user wants to rebase, do that first
 	if flag rebase; then
-		if ! git flow feature rebase "$candidate"; then
+    local _rebase_opts=""
+		if flag preservemerge; then
+			_rebase_opts="$_rebase_opts -p"
+		fi
+		if ! git flow feature rebase $_rebase_opts "$NAME"; then
 			warn "Finish was aborted due to conflicts during rebase."
 			warn "Please finish the rebase manually now."
 			warn "When finished, re-run:"
-			warn "    git flow feature finish '$candidate' '$base'"
+			warn "    git flow feature finish '$NAME' '$base'"
 			exit 1
 		fi
 	fi
 
   # Merge into BASE
-	git_checkout "$base" || die "Could not check out branch '$BASE_BRANCH'."
-  if [ "$(git rev-list -n2 "$base..$candidate_branch" | wc -l)" -eq 1 ]; then
-				git_do merge --ff "$candidate_branch"
+	git_checkout "$base" || die "Could not check out branch '$base'."
+  if [ "$(git rev-list -n2 "$base..$BRANCH" | wc -l)" -eq 1 ]; then
+				git merge --ff "$candidate_branch"
 	else
-				git_do merge --no-ff "$candidate_branch"
+				git merge --no-ff "$candidate_branch"
   fi
 
   if [ $? -ne 0 ]; then
@@ -151,80 +219,208 @@ finish(){
     exit 1
   fi
 
-  flow_unset_branch_base "$candidate_branch"
-  cleanup
+  flow_unset_branch_base "$BRANCH"
+  finish_cleanup
 
 }
 
-cleanup(){
-  require_branch "$candidate_branch"
+finish_cleanup(){
+  require_branch "$BRANCH"
   require_clean_working_tree
 
   if ! flag keep; then
-    if git_remote_branch_exists "$ORIGIN/$candidate_branch"; then
-      git_remote_branch_delete "$candidate_branch"
+    if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+      git_remote_branch_delete "$BRANCH"
     fi
 
-    if equals "$candidate_branch" "$(git stats --long-current-branch)"; then
+    if equals "$BRANCH" "$(git stats --long-current-branch)"; then
       git_checkout "$base" || die "Could not checkout $base."
     fi
 
-    git branch -d "$candidate_branch"
-    flow_remove_branch_section "$candidate_branch"
+    git branch -d "$BRANCH" && flow_remove_branch_section "$BRANCU"
   fi
 
   if flag push; then
     git push "$ORIGIN" "$base" || die "Could not push changes from $base to $ORIGIN."
   fi
+
+  note "Feature __${BRANCH}__ was merged into __${base}__."
+  if ! flag keep; then
+    note "Feature __${BRANCH}__ was removed."
+  fi
+  note "You are in branch $(git stats --long-current-branch)."
+
+}
+
+publish(){
+  USAGE="\
+git flow feature publish [-h] [<name>]
+
+Publish feature branch <name> on $ORIGIN.
+When <name> is omitted the current branch is used, but only if it's a feature branch.
+
+    -h          Show this help
+"
+  # Parse arguments
+  parse_args "$@"
+
+  # Use current branch if no name is given
+  if EMPTY "$NAME"; then
+    NAME=$(git stats --long-current-branch)
+    BRANCH=$NAME
+  fi
+
+  # Sanity checks
+  require_clean_working_tree
+  require_branch "$BRANCH"
+
+  # Create remote branch with remote tracking
+  git push -u "$ORIGIN" "$BRANCH:$BRANCH"
+  git_fetch "$ORIGIN" "$BRANCH" || die "Could not fetch branch '$BRANCH' from remote '$ORIGIN'."
+  git_checkout "$BRANCH" || die "Could not check out branch '$BRANCH'."
+
+  note "- The remote branch '$BRANCH' was created or updated"
+  note "- The local branch '$BRANCH' was configured to track the remote branch"
+  note "You are in branch $(git stats --long-current-branch)."
+}
+
+track() {
+	USAGE="\
+git flow feature track [-h] <name>
+
+Start tracking feature <name> that is shared on $ORIGIN
+
+    -h         Show this help
+"
+	# Parse arguments
+	parse_args "$@"
+
+	! empty "$NAME" || die "No branch name passed."
+
+	# Sanity checks
+	require_clean_working_tree
+	require_local_branch_absent "$BRANCH"
+require_remote_branch "$ORIGIN/$BRANCH"
+
+	# Create tracking branch
+	git_checkout "$BRANCH" "$ORIGIN/$BRANCH" || die "Could not create '$BRANCH'."
+
+	note "A new remote tracking branch '$BRANCH' was created"
+	note "You are in branch $(git stats --long-current-branch)."
+}
+
+diff() {
+	USAGE="\
+git flow feature diff [-h] [<name|nameprefix>]
+
+Show all changes in <name> that are not in the base
+    -h          Show this help
+"
+	local base
+
+	# Parse arguments
+	parse_args "$@"
+
+  # Use current branch if no name is given
+  if EMPTY "$NAME"; then
+    NAME=$(git stats --long-current-branch)
+    BRANCH=$NAME
+  fi
+
+	base=$(flow_get_branch_base $BRANCH)
+	base=${base:-$DEVELOP_BRANCH}
+
+	git diff "$base..$BRANCH"
 }
 
 rebase() {
+  USAGE="\
+  git flow feature rebase [-h] [-i] [-p] [<name|nameprefix>]
 
-	# Define flags
-	DEFINE_boolean 'interactive' false 'do an interactive rebase' i
-	DEFINE_boolean 'preserve-merges' false 'try to recreate merges' p
+  Rebase <name> on <base_branch>
+      -h                 Show this help
+      -i                 Do an interactive rebase
+      --preserve-merges  Preserve merges
+  "
 
   for arg do
     shift
     case "$arg" in
       -i) set_flag interactive; ;;
-      --preserve-merges) set_flag preserve; ;;
+      --preserve-merges) set_flag preservemerges; ;;
       *) set -- "$@" "$arg"; ;;
     esac
   done
 	# Parse arguments
 	parse_args "$@"
 
-	if empty "$candidate"; then
-    candidate=$(git stats --long-current-branch)
-    candidate_branch=$prefix$candidate
+	if empty "$NAME"; then
+    NAME=$(git stats --long-current-branch)
+    BRANCH=$NAME
   fi
-  require_branch_prefix "$candidate_branch" "$prefix"
-  require_branch "$candidate_branch"
-  base=$(flow_get_branch_base "$candidate_branch")
+  require_branch_prefix "$BRANCH" "$prefix"
+  require_branch "$BRANCH"
+  base=$(flow_get_branch_base "$BRANCH")
   base=${base:-$DEVELOP_BRANCH}
   require_local_branch "$base"
 
 	require_clean_working_tree
 
-	git_checkout "$candidate_branch"  || die "Could not check out branch $candidate_branch."
+	git_checkout "$BRANCH"  || die "Could not check out branch $candidate_branch."
 	if flag interactive; then
 		opts="$opts -i"
 	fi
-	if flag preserve; then
+	if flag preservemerges; then
 		opts="$opts -p"
 	fi
 	git rebase $opts "$base"
 }
 
-avoid_accidental_cross_branch_action() {
+delete(){
+  USAGE="\
+git flow feature delete [-h] [-f] [-r] <name>
+
+Delete a given feature branch
+
+    -h          Show this help
+    --remote    Delete remote branch
+"
 	local current_branch
 
-	current_branch=$(git_current_branch)
-	if [ "$BRANCH" != "$current_branch" ]; then
-		warn "Trying to pull from '$BRANCH' while currently on branch '$current_branch'."
-		warn "To avoid unintended merges, git-flow aborted."
-		return 1
+	# Parse arguments
+	parse_args "$@"
+
+	! empty "$NAME" || die "No branch name passed."
+
+	# Sanity checks
+	require_branch "$BRANCH"
+
+	BASE_BRANCH=$(flow_get_branch_base $BRANCH)
+	BASE_BRANCH=${BASE_BRANCH:-$DEVELOP_BRANCH}
+
+	current_branch=$(git stats --long-current-branch)
+	# We can't delete a branch we are on, switch to the develop branch.
+	if equals "$BRANCH" "$current_branch"; then
+		require_clean_working_tree
+		if git_local_branch_exists "$BASE_BRANCH"; then
+			git_checkout "$BASE_BRANCH"
+		else
+			git_checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
+		fi
 	fi
-	return 0
+
+	if git_is_branch_merged_into "$BRANCH" "$BASE_BRANCH"; then
+		git branch -d "$BRANCH" || die "Could not delete the $BRANCH."
+		if flag remote; then
+			git push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
+		fi
+	else
+		die "Feature branch '$BRANCH' has been not been merged yet. "
+	fi
+
+	flow_unset_branch_base"$BRANCH"
+
+	note "Feature branch '$BRANCH' has been deleted."
+	flag remote && note "Feature branch '$BRANCH' in '$ORIGIN' has been deleted."
+	note "You are in branch $(git stats --long-current-branch)."
 }
diff --git a/bin/git-flow-hotfix b/bin/git-flow-hotfix
--- a/bin/git-flow-hotfix
+++ b/bin/git-flow-hotfix
@@ -7,7 +7,50 @@ source $(git stats --script-location $0)/git-common
 git_get flow.prefix.hotfix >/dev/null 2>&1 || die "Flow is not using hotfix branches. Use 'git flow init -f' to reconfigure."
 prefix=$(git_get flow.prefix.hotfix)
 
+# Parse arguments and set common variables
+parse_args() {
+  case "$1" in
+    -h ) usage ;;
+    * ) VERSION="$1"
+  esac
+
+  if ! empty "$VERSION"; then
+    if startswith "$VERSION" "$prefix"; then
+      VERSION=${VERSION##$prefix}
+    fi
+    BRANCH="$prefix$VERSION"
+  fi
+}
+
+help() {
+USAGE='' && read -r -d '' USAGE <<'EOF'
+git flow hotfix [list]
+git flow hotfix start
+git flow hotfix finish
+git flow hotfix publish
+git flow hotfix delete
+
+Manage your hotfix branches.
+
+For more specific help type the command followed by --help
+EOF
+	usage
+}
+
+default() {
+  list "$@"
+}
+
 list(){
+  USAGE="\
+git flow hotfix [list] [-h] [-v]
+
+Lists all local hotfix branches
+
+    -h           Show this help
+    -v           Verbose (more) output
+"
+  parse_args "$@"
   local hotfix_branchs base master_hash branch_hash
   hotfix_branchs=$(git_local_branches_with_prefix "$prefix")
   if empty $hotfix_branchs; then
@@ -46,16 +89,405 @@ list(){
   done
 }
 
-start(){
-  git bump -R --hotfix --commit $MASTER_BRANCH
+require_no_existing_hotfix_branches() {
+	local hotfix_branches first_branch
+
+	hotfix_branches=$(git_local_branches_prefixed "$PREFIX")
+	first_branch=$(echo ${hotfix_branches} | head -n1)
+
+	first_branch=${first_branch#$PREFIX}
+	[ -z "$hotfix_branches" ] || die "There is an existing hotfix branch '$first_branch'. Finish that one first."
 }
 
-finish(){
-      BRANCH=${1:-`git stats --current-branch`}
-      git_checkout $MASTER_BRANCH && git merge --no-ff $prefix$BRANCH && git_checkout $DEVELOP_BRANCH && git merge --no-ff $prefix$BRANCH && git_checkout $prefix$BRANCH;
+start() {
+	USAGE="\
+git flow hotfix start [-h] [-F] <version> [<base>]
+
+Start new hotfix branch named <version>, optionally base it on <base> instead of the <master> branch
+
+    -h              Show this help
+    --fetch         Fetch from $ORIGIN before performing finish
+    -v              Verbose (more) output
+"
+	local base
+
+  for arg do
+    shift
+    case "$arg" in
+      --fetch) set_flag fetch; ;;
+      *) set -- "$@" "$arg"; ;;
+    esac
+  done
+	# Parse arguments
+	parse_args "$@"
+	base=${2:-$MASTER_BRANCH}
+
+	# No need to continue if not clean
+	require_local_branch "$base"
+	require_clean_working_tree
+  ! gadgets_bump_is_initialized || set_flag bump
+	require_local_branch "$base"
+  if flag bump; then
+    if empty "$VERSION"; then
+      git bump minor --no-tag --branch="$prefix" "$base"
+    else
+      git bump --version="$VERSION" --no-tag --branch="$prefix" "$base"
+    fi
+    BRANCH=$(git stats --long-current-branch) #retrieve branch name.
+  else
+    ! empty "$VERSION" || die "No version passed."
+    # Sanity checks
+    require_clean_working_tree
+    require_branch_absent "$BRANCH"
+    if flag fetch; then
+  		git_fetch_branch "$ORIGIN" "$base"
+  	fi
+  	if git_remote_branch_exists "$ORIGIN/$base"; then
+  		require_branches_equal "$base" "$ORIGIN/$base"
+  	fi
+    git_checkout "$BRANCH" "$base" || die "Could not create release branch '$BRANCH'."
+  fi
+
+  flow_set_branch_base $BRANCH $base
+	note "- A new branch '$BRANCH' was created, based on '$base'"
+  note "- You are now on branch '$(git stats --long-current-branch)'"
 }
 
-push(){
-        BRANCH=${1:-`git stats --current-branch`}
-        git push $ORIGIN $MASTER_BRANCH && git push $ORIGIN $DEVELOP_BRANCH && git push $ORIGIN --tags && git_checkout $DEVELOP_BRANCH && git branch -d $prefix$BRANCH;
+publish() {
+	USAGE="\
+git flow hotfix publish [-h] <version>
+
+Start sharing hotfix <name> on $ORIGIN
+
+    -h           Show this help
+"
+	# Parse arguments
+	parse_args "$@"
+
+  # Use current branch if no version is given
+  if empty "$VERSION"; then
+    BRANCH=$(git stats --long-current-branch)
+    VERSION=${BRANCH##$prefix}
+  fi
+
+	# Sanity checks
+	require_clean_working_tree
+	require_branch "$BRANCH"
+	require_branch_absent "$ORIGIN/$BRANCH"
+
+	# Create remote branch with remote tracking
+	git push -u "$ORIGIN" "$BRANCH:$BRANCH"
+	git_fetch_branch "$ORIGIN" "$BRANCH" || die "Could not fetch branch '$BRANCH' from remote '$ORIGIN'."
+	git_checkout "$BRANCH" || die "Could not check out branch '$BRANCH'."
+
+  note "- The remote branch '$BRANCH' was created or updated"
+  note "- The local branch '$BRANCH' was configured to track the remote branch"
+  note "- You are now on branch '$(git stats --long-current-branch)'"
+}
+
+rebase() {
+	USAGE="\
+git flow hotfix rebase [-h] [-i] [-p] [<name|nameprefix>]
+
+Rebase <name> on <base_branch>
+
+    -h                 Show this help
+    -i                 Do an interactive rebase
+    --preserve-merges  Preserve merges
+"
+	local opts
+  for arg do
+    shift
+    case "$arg" in
+      -i) set_flag interactive; ;;
+      --preserve-merges) set_flag preservemerges; ;;
+      *) set -- "$@" "$arg"; ;;
+    esac
+  done
+	# Parse arguments
+	parse_args "$@"
+
+  # Use current branch if no version is given
+  if empty "$VERSION"; then
+    BRANCH=$(git stats --long-current-branch)
+    VERSION=${BRANCH##$prefix}
+  fi
+
+	BASE_BRANCH=$(flow_get_branch_base $BRANCH)
+	BASE_BRANCH=${BASE_BRANCH:-$DEVELOP_BRANCH}
+
+	require_clean_working_tree
+	require_branch "$BRANCH"
+
+	git_local_branch_exists "$BASE_BRANCH" || die "The base '$BASE_BRANCH' doesn't exists locally or is not a branch. Can't rebase the hotfixe branch '$BRANCH'."
+
+	if flag interactive; then
+		opts="$opts -i"
+	fi
+	if flag preserve_merges; then
+		opts="$opts -p"
+	fi
+	git rebase $opts "$BASE_BRANCH"
+}
+
+track() {
+	USAGE="\
+git flow hotfix track [-h] <version>
+
+Create a tracking hotfix branch from $ORIGIN
+
+    -h           Show this help
+"
+	# Parse arguments
+	parse_args "$@"
+
+		! empty "$VERSION" || die "No release version passed."
+
+	# Sanity checks
+	require_clean_working_tree
+	require_branch_absent "$BRANCH"
+	require_branch "$ORIGIN/$BRANCH"
+
+	# Create tracking branch
+	git_checkout -b "$BRANCH" "$ORIGIN/$BRANCH"
+
+  note "- A new remote tracking branch '$BRANCH' was created"
+	note "- You are now on branch '$(git stats --long-current-branch)'"
+}
+
+cmd_finish() {
+	USAGE="\
+git flow hotfix finish [-h] [-F] [-s] [-u] [-m | -f ] [-p] [-k] [-n] [-b] [-S] <version>
+
+Finish hotfix branch <version>
+
+    -h              Show this help
+    --fetch         Fetch from origin before performing finish
+    -s|--sign             Sign the release tag cryptographically
+    --push          Push to origin after performing finish
+    --keep          Keep branch after performing finish
+    --no-tag           Don't tag this release
+"
+	local opts commit keepmsg remotebranchdeleted localbranchdeleted
+
+  for arg do
+    shift
+    case "$arg" in
+      --fetch) set_flag fetch; ;;
+      -s|--sign) set_flag sign ;;
+      --push) set_flag push ;;
+      --keep) set_flag keep ;;
+      --no-tag) set_flag notag ;;
+      *) set -- "$@" "$arg"; ;;
+    esac
+  done
+	# Parse arguments
+	parse_args "$@"
+
+  # Use current branch if no version is given
+  if empty "$VERSION"; then
+    BRANCH=$(git stats --long-current-branch)
+    VERSION=${BRANCH##$prefix}
+  fi
+
+  # Use branch name if no tag name is given
+  TAGNAME=$VERSION
+
+	# Sanity checks
+	require_branch "$BRANCH"
+	require_clean_working_tree
+
+	BASE_BRANCH=$(flow_get_branch_base $BRANCH)
+	BASE_BRANCH=${BASE_BRANCH:-$MASTER_BRANCH}
+	git_local_branch_exists "$BASE_BRANCH" || die "The base '$BASE_BRANCH' doesn't exists locally or is not a branch. Can't finish the hotfix branch '$BRANCH'."
+
+	# We always fetch the Branch from Origin
+	# This is done to avoid possible commits on the remote that are not
+	# merged into the local branch
+	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+		git_fetch_branch "$ORIGIN" "$BRANCH"
+	fi
+
+	# Update local branches with remote branches
+	if flag fetch; then
+		git_fetch_branch "$ORIGIN" "$BASE_BRANCH"
+		[ "$BASE_BRANCH" = "$MASTER_BRANCH" ] && git_fetch_branch "$ORIGIN" "$DEVELOP_BRANCH"
+	fi
+
+	# Check if the local branches have all the commits from the remote branches
+	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
+	fi
+	if git_remote_branch_exists "$ORIGIN/$BASE_BRANCH"; then
+		require_branches_equal "$BASE_BRANCH" "$ORIGIN/$BASE_BRANCH"
+	fi
+	if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
+		if git_remote_branch_exists "$ORIGIN/$DEVELOP_BRANCH"; then
+			require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
+		fi
+	fi
+
+	# If the branch is already merged there is no need to check the hotfix branch
+	# This can happen when the merge in develop fails and we rerun the finish.
+	if ! git_is_branch_merged_into "$BRANCH" "$BASE_BRANCH"; then
+		# Check if the hotfix branch:
+		# - has commits: No reason to finish a hotfix without commits
+		# - Is ahead of the BASE: If it's not a good idea to merge
+		# - Can be merged: If there's no common ancestor we can't merge the hotfix
+		git_compare_refs "$BRANCH" "$BASE_BRANCH"
+		case $? in
+		0)
+			die "You need some commits in the hotfix branch '$BRANCH'"
+			;;
+		1)
+			die "The hotfix branch '$BRANCH' is not ahead of branch '$BASE_BRANCH'"
+			;;
+		4)
+			die "The hotfix branch '$BRANCH' has no common ancestor with branch '$BASE_BRANCH'"
+			;;
+		*)
+			;;
+		esac
+	fi
+
+	if noflag notag && ! flag bump; then
+		# We ask for a tag, be sure it does not exists or
+		# points to the latest hotfix commit
+		if git_tag_exists "$VERSION_PREFIX$TAGNAME"; then
+			git_compare_refs  "$BRANCH" "$VERSION_PREFIX$TAGNAME"^2 2>/dev/null
+			[ $? -eq 0 ] || die "Tag already exists and does not point to hotfix branch '$BRANCH'"
+		fi
+	fi
+
+	# Try to merge into BASE.
+	# In case a previous attempt to finish this release branch has failed,
+	# but the merge into BASE was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "$BASE_BRANCH"; then
+		git_checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
+		git merge --no-ff "$BRANCH" || die "There were merge conflicts." # TODO: What do we do now?
+
+	fi
+
+  if ! flag notag; then
+		# Try to tag the release.
+		# In case a previous attempt to finish this release branch has failed,
+		# but the tag was set successful, we skip it now
+    git_checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
+    if flag bump; then
+      git bump tag
+    else
+      if ! git_tag_exists "$VERSION_PREFIX$TAGNAME"; then
+		    opts="-a"
+  			flag sign && opts="$opts -s"
+  			git tag $opts "$VERSION_PREFIX$TAGNAME" || die "Tagging failed. Please run finish again to retry."
+  		fi
+    fi
+	fi
+
+	if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
+		# By default we back-merge the $MASTER_BRANCH unless the user explicitly
+		# stated not to do a back-merge, in that case we use the $BRANCH.
+		merge_branch="$MASTER_BRANCH"
+
+		# Try to merge into develop.
+		# In case a previous attempt to finish this release branch has failed,
+		# but the merge into develop was successful, we skip it now
+		if ! git_is_branch_merged_into "$MERGE_BRANCH" "$DEVELOP_BRANCH"; then
+			git_checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
+
+			git merge --no-ff "$BRANCH" || die "There were merge conflicts." # TODO: What do we do now?
+		fi
+	fi
+
+	# Delete branch
+	if ! flag keep; then
+
+		if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+			git_remote_branch_delete "$BRANCH"
+		fi
+
+		if [ "$BRANCH" = "$(git stats --long-current-branch)" ]; then
+			git checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
+		fi
+		git branch -d "$BRANCH"
+
+		# no more branches: we can safely remove config section
+		if ! git_remote_branch_exists "$ORIGIN/$BRANCH" -a ! git_local_branch_exists "$BRANCH"; then
+			flow_remove_branch_section "$BRANCH"
+		fi
+
+	fi
+
+	if flag push; then
+		if equals "$BASE_BRANCH" "$MASTER_BRANCH"; then
+			git push "$ORIGIN" "$DEVELOP_BRANCH" || die "Could not push branch '$DEVELOP_BRANCH' to remote '$ORIGIN'."
+		fi
+		git push "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
+		if ! flag notag; then
+			git push --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
+		fi
+	fi
+
+	if flag fetch; then
+		note "Latest objects have been fetched from '$ORIGIN'"
+	fi
+	note "Hotfix branch '$BRANCH' has been merged into '$BASE_BRANCH'"
+	if ! flag notag; then
+		echo "The hotfix was tagged."
+	fi
+
+	if ! flag keep; then
+	     note "- Hotfix branch '$BRANCH' was removed."
+	fi
+	if flag push; then
+		if equals "$BASE_BRANCH" "$MASTER_BRANCH"; then
+			note "'$DEVELOP_BRANCH', '$BASE_BRANCH' and tags have been pushed to '$ORIGIN'"
+		else
+			note "'$BASE_BRANCH' and tags have been pushed to '$ORIGIN'"
+		fi
+	fi
+	note "- You are now on branch '$(git stats --long-current-branch)'"
+}
+
+delete() {
+	USAGE="\
+git flow hotfix delete [-h] [-f] [-r] <name>
+
+Delete the given hotfix branch
+
+    -h          Show this help
+    --remote    Delete remote branch
+"
+	local current_branch
+
+
+	# Parse arguments
+	parse_args "$@"
+
+	! empty "$VERSION" || die "No version passed."
+
+	# Sanity checks
+	require_branch "$BRANCH"
+
+	current_branch=$(git stats --long-current-branch)
+	# We can't delete a branch we are on, switch to the master branch.
+	if equals "$BRANCH" "$current_branch"; then
+		require_clean_working_tree
+		git_checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
+	fi
+
+	if ( git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH" && git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH" ); then
+		git branch -d "$BRANCH" || die "Could not delete the $BRANCH."
+		if flag remote; then
+			git push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
+		fi
+	else
+		die "Hotfix branch '$BRANCH' has been not been merged in branch '$MASTER_BRANCH' and/or branch '$DEVELOP_BRANCH'. Use -f to force the deletion."
+	fi
+
+	flow_remove_branch_section "$BRANCH"
+
+  note "Hotfix branch '$BRANCH' has been deleted."
+	flag remote && note "Hotfix branch '$BRANCH' in '$ORIGIN' has been deleted."
+	note "You are now on branch '$(git_current_branch)'"
 }
diff --git a/bin/git-flow-release b/bin/git-flow-release
--- a/bin/git-flow-release
+++ b/bin/git-flow-release
@@ -2,12 +2,179 @@
 
 SUBDIRECTORY_OK="yes"
 
-source $(git stats --script-location $0)/git-common
+source $(git stats --script-location $0)/git-flow-common
 
 git_get flow.prefix.release >/dev/null 2>&1 || die "Flow is not using release branches. Use 'git flow init -f' to reconfigure."
 prefix=$(git_get flow.prefix.release)
 
+#
+# Function used by finish command to actually finish the release branch
+# Called when the base of the release is the $DEVELOP_BRANCH
+#
+_finish() {
+	local opts merge_branch commit keepmsg remotebranchdeleted localbranchdeleted compare_refs_result merge_result
+
+	remotebranchdeleted=$FLAGS_FALSE
+	localbranchdeleted=$FLAGS_FALSE
+
+	# Update local branches with remote branches
+	if flag fetch; then
+		git_fetch_branch "$ORIGIN" "$MASTER_BRANCH"
+		git_fetch_branch "$ORIGIN" "$DEVELOP_BRANCH"
+	fi
+
+	# Check if the local branches have all the commits from the remote branches
+	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
+	fi
+	if git_remote_branch_exists "$ORIGIN/$MASTER_BRANCH"; then
+			git_compare_refs "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
+			compare_refs_result=$?
+
+			if [ $compare_refs_result -gt 0 ]; then
+				warn "Branches '"$MASTER_BRANCH"' and '"$ORIGIN/$MASTER_BRANCH"' have diverged."
+				if [ $compare_refs_result -eq 1 ]; then
+					warn "Fast forwarding '"$MASTER_BRANCH"'."
+					git_checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
+					git merge  --ff-only "$ORIGIN/$MASTER_BRANCH" >/dev/null 2>&1
+					merge_result=$?
+					git_checkout "$BRANCH"
+					if [ $merge_result -gt 0 ]; then
+						die "'"$MASTER_BRANCH"' can not be fast forwarded."
+					fi
+				elif [ $compare_refs_result -eq 2 ]; then
+					# Warn here, since there is no harm in being ahead
+					warn "And local branch '$1' is ahead of '$2'."
+				else
+					die "Branches need merging first."
+				fi
+			fi
+	fi
+	if git_remote_branch_exists "$ORIGIN/$DEVELOP_BRANCH"; then
+		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
+	fi
+
+	if ! flag notag && ! flag bump; then
+		# We ask for a tag, be sure it does not exists or
+		# points to the latest hotfix commit
+		if git_tag_exists "$VERSION_PREFIX$TAGNAME"; then
+			git_compare_refs  "$BRANCH" "$VERSION_PREFIX$TAGNAME"^2 2>/dev/null
+			[ $? -eq 0 ] || die "Tag already exists and does not point to release branch '$BRANCH'"
+		fi
+	fi
+
+	# Try to merge into master.
+	# In case a previous attempt to finish this release branch has failed,
+	# but the merge into master was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
+			git_checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
+			git_do merge --no-ff "$BRANCH" || die "There were merge conflicts." # TODO: What do we do now?
+
+	fi
+
+	if ! flag notag; then
+		# Try to tag the release.
+		# In case a previous attempt to finish this release branch has failed,
+		# but the tag was set successful, we skip it now
+    git_checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
+    if flag bump; then
+      git bump tag
+    else
+      if ! git_tag_exists "$VERSION_PREFIX$TAGNAME"; then
+		    opts="-a"
+  			flag sign && opts="$opts -s"
+  			git tag $opts "$VERSION_PREFIX$TAGNAME" || die "Tagging failed. Please run finish again to retry."
+  		fi
+    fi
+	fi
+
+	merge_branch="$MASTER_BRANCH"
+
+	# Try to merge into develop.
+	# In case a previous attempt to finish this release branch has failed,
+	# but the merge into develop was successful, we skip it now
+	if ! git_is_branch_merged_into "$merge_branch" "$DEVELOP_BRANCH"; then
+		git_checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
+		git merge --no-ff "$MASTER_BRANCH" || die "There were merge conflicts." # TODO: What do we do now?
+	fi
+
+	# Delete branch
+	if ! flag keep; then
+
+		if equals "$BRANCH" "$(git stats --long-current-branch)"; then
+			git_checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
+		fi
+
+		# Always delete remote first
+		if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+			git_remote_branch_delete "$BRANCH"
+		fi
+
+		# Delete local after remote to avoid warnings
+		git branch -d "$BRANCH"
+
+
+		# no more branches: we can safely remove config section
+		if ! git_remote_branch_exists "$ORIGIN/$BRANCH" -a ! git_local_branch_exists "$BRANCH"; then
+			flow_remove_branch_section "$BRANCH"
+		fi
+	fi
+
+	if flag push; then
+	    git push "$ORIGIN" "$DEVELOP_BRANCH" || die "Could not push branch '$DEVELOP_BRANCH' to remote '$ORIGIN'."
+	    git push "$ORIGIN" "$MASTER_BRANCH" || die "Could not push branch '$MASTER_BRANCH' to remote '$ORIGIN'."
+      git push --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
+	fi
+
+	if flag fetch; then
+		note "Latest objects have been fetched from '$ORIGIN'"
+	fi
+	note "Release branch '$BRANCH' has been merged into '$MASTER_BRANCH'"
+	if ! flag notag; then
+		note "The release was tagged."
+	fi
+
+	if ! flag keep; then
+	  note "- Release branch '$BRANCH' was removed."
+	fi
+
+	if flag push; then
+		note "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+	fi
+	note "- You are now on branch '$(git stats --long-current-branch)'"
+}
+
+help(){
+USAGE='' && read -r -d '' USAGE <<'EOF'
+release
+git flow release [list]
+git flow release start
+git flow release finish
+git flow release publish
+git flow release track
+git flow release delete
+
+Manage your release branches.
+
+For more specific help type the command followed by -h
+EOF
+  usage
+}
+
+default() {
+	list "$@"
+}
+
 list(){
+  USAGE="\
+release [list] [-h] [-v]
+
+Lists all the existing release branches in the local repository.
+
+    -h   Show help
+    -v   Verbose output
+"
+  parse_args "$@"
   local release_branchs base develop_hash branch_hash
   release_branchs=$(git_local_branches_with_prefix "$prefix")
   if empty $release_branchs; then
@@ -38,20 +205,284 @@ list(){
     fi
     echo
   done
-
 }
 
-start(){
-  git bump -R --release --commit
+parse_args(){
+  case "$1" in
+    -h ) usage ;;
+    * ) VERSION="$1"
+  esac
+
+  if ! empty "$VERSION"; then
+    if startswith "$VERSION" "$prefix"; then
+      VERSION=${VERSION##$prefix}
+    fi
+    BRANCH="$prefix$VERSION"
+  fi
 }
 
-finish(){
-  BRANCH=${1:-`git stats --current-branch`}
-  git bump --tag
-  git_checkout $MASTER_BRANCH && git merge --no-ff $prefix$BRANCH && git_checkout $DEVELOP_BRANCH && git merge --no-ff $prefix$BRANCH && git_checkout $prefix$BRANCH;
+require_no_existing_release_branches() {
+	local release_branches first_branch
+
+	release_branches=$(git_local_branches_prefixed "$prefix")
+	first_branch=$(echo ${release_branches} | head -n1)
+
+	first_branch=${first_branch#$prefix}
+	[ -z "$release_branches" ] || die "There is an existing release branch '$first_branch'. Finish that one first."
 }
 
-push(){
-  BRANCH=${1:-`git stats --current-branch`}
-  git push $ORIGIN $MASTER_BRANCH && git push $ORIGIN $DEVELOP_BRANCH && git push $ORIGIN --tags && git_checkout $DEVELOP_BRANCH &&  git branch -d $prefix$BRANCH;
+start() {
+	USAGE="\
+git flow release start [options] <version> [<base>]
+
+Start a new release branch
+
+    -h              Show this help
+    --fetch         Fetch from $ORIGIN before performing finish
+    -v              Verbose (more) output
+"
+	local base
+
+  for arg do
+    shift
+    case "$arg" in
+      --fetch) set_flag fetch; ;;
+      *) set -- "$@" "$arg"; ;;
+    esac
+  done
+  parse_args "$@"
+	base=${2:-$DEVELOP_BRANCH}
+
+  ! gadgets_bump_is_initialized || set_flag bump
+	require_local_branch "$base"
+  if flag bump; then
+    if empty "$VERSION"; then
+      git bump --no-tag --branch="$prefix" "$base"
+    else
+      git bump --version="$VERSION" --no-tag --branch="$prefix" "$base"
+    fi
+    BRANCH=$(git stats --long-current-branch) #retrieve branch name.
+  else
+    ! empty "$VERSION" || die "No version passed."
+    require_no_existing_release_branches
+    # Sanity checks
+    require_clean_working_tree
+    require_branch_absent "$BRANCH"
+    if flag fetch; then
+  		git_fetch_branch "$ORIGIN" "$base"
+  	fi
+  	if git_remote_branch_exists "$ORIGIN/$base"; then
+  		require_branches_equal "$base" "$ORIGIN/$base"
+  	fi
+    git_checkout "$BRANCH" "$base" || die "Could not create release branch '$BRANCH'."
+  fi
+
+	flow_set_branch_base $BRANCH $base
+	note "- A new branch '$BRANCH' was created, based on '$base'"
+  note "- You are now on branch '$(git stats --long-current-branch)'"
+}
+
+finish() {
+	USAGE="\
+git flow release finish [-h] [-F] [-s] [-u] [-m | -f] [-p] [-k] [-n] [-b] [-S] <version>
+
+Finish a release branch
+
+    -h              Show this help
+    --fetch         Fetch from origin before performing finish
+    -s|--sign             Sign the release tag cryptographically
+    --push          Push to origin after performing finish
+    --keep          Keep branch after performing finish
+    --no-tag           Don't tag this release
+"
+  for arg do
+    shift
+    case "$arg" in
+      --fetch) set_flag fetch; ;;
+      -s|--sign) set_flag sign ;;
+      --push) set_flag push ;;
+      --keep) set_flag keep ;;
+      --no-tag) set_flag notag ;;
+      *) set -- "$@" "$arg"; ;;
+    esac
+  done
+	# Parse arguments
+	parse_args "$@"
+
+	# Use current branch if no version is given
+	if empty "$VERSION"; then
+		BRANCH=$(git stats --long-current-branch)
+    VERSION=${BRANCH##$prefix}
+	fi
+
+	# Use branch name if no tag name is given
+	TAGNAME=$VERSION
+
+	BASE_BRANCH=$(flow_get_branch_base $BRANCH)
+	BASE_BRANCH=${BASE_BRANCH:-$DEVELOP_BRANCH}
+	git_local_branch_exists "$BASE_BRANCH" || die "The base '$BASE_BRANCH' doesn't exists locally or is not a branch. Can't finish the release branch '$BRANCH'."
+
+	# Sanity checks
+	require_branch "$BRANCH"
+	require_clean_working_tree
+
+	# We always fetch the Branch from Origin
+	# This is done to avoid possible commits on the remote that are not
+	# merged into the local branch
+	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+			git_fetch_branch "$ORIGIN" "$BRANCH"
+	fi
+		_finish
+}
+
+publish() {
+	USAGE="\
+git flow release publish [-h] <name>
+
+Publish the release branch <name> on $ORIGIN
+
+    -h           Show this help
+"
+	# Parse arguments
+	parse_args "$@"
+
+  # Use current branch if no version is given
+	if empty "$VERSION"; then
+		BRANCH=$(git stats --long-current-branch)
+    VERSION=${BRANCH##$prefix}
+	fi
+
+	# Sanity checks
+	require_clean_working_tree
+	require_branch "$BRANCH"
+	require_branch_absent "$ORIGIN/$BRANCH"
+
+	# Create remote branch with remote tracking
+	git push -u "$ORIGIN" "$BRANCH:$BRANCH"
+	git_fetch_branch "$ORIGIN" "$BRANCH" || die "Could not fetch branch '$BRANCH' from remote '$ORIGIN'."
+	git_checkout "$BRANCH" || die "Could not check out branch '$BRANCH'."
+
+	note "- The remote branch '$BRANCH' was created or updated"
+	note "- The local branch '$BRANCH' was configured to track the remote branch"
+	note "- You are now on branch '$(git stats --long-current-branch)'"
+}
+
+track() {
+	USAGE="\
+git flow release track [-h] <name>
+
+Start tracking release <name> that is shared on $ORIGIN
+
+    -h           Show this help
+"
+	# Parse arguments
+	parse_args "$@"
+
+	! empty "$VERSION" || die "No release version passed."
+
+	# Sanity checks
+	require_clean_working_tree
+	require_local_branch_absent "$BRANCH"
+	git_remote_branch_exists "$ORIGIN/$BRANCH"
+
+	# Create tracking branch
+	git_checkout "$BRANCH" "$ORIGIN/$BRANCH" || die "Could not create branch '$BRANCH'."
+
+	note "- A new remote tracking branch '$BRANCH' was created"
+	note "- You are now on branch '$(git stats --long-current-branch)'"
+}
+
+rebase() {
+	USAGE="\
+git flow release rebase [-h] [-i] [-p] [<name|nameprefix>]
+
+Rebase <name> on <base_branch>
+
+    -h                 Show this help
+    -i                 Do an interactive rebase
+    --preserve-merges  Preserve merges
+"
+	local opts
+
+  for arg do
+    shift
+    case "$arg" in
+      -i) set_flag interactive; ;;
+      --preserve-merges) set_flag preservemerges; ;;
+      *) set -- "$@" "$arg"; ;;
+    esac
+  done
+	# Parse arguments
+	parse_args "$@"
+
+  # Use current branch if no version is given
+  if empty "$VERSION"; then
+    BRANCH=$(git stats --long-current-branch)
+    VERSION=${BRANCH##$prefix}
+  fi
+
+	BASE_BRANCH=$(flow_get_branch_base $BRANCH)
+	BASE_BRANCH=${BASE_BRANCH:-$DEVELOP_BRANCH}
+
+	require_clean_working_tree
+	require_branch "$BRANCH"
+
+	git_local_branch_exists "$BASE_BRANCH" || die "The base '$BASE_BRANCH' doesn't exists locally or is not a branch. Can't rebase the release branch '$BRANCH'."
+
+	if flag interactive; then
+		opts="$opts -i"
+	fi
+	if flag preservemerges; then
+		opts="$opts -p"
+	fi
+	git rebase $opts "$BASE_BRANCH"
+}
+
+delete() {
+	USAGE="\
+git flow release delete [-h] [-f] [-r] <name>
+
+Delete the given release branch
+
+    -h          Show this help
+    --remote    Delete remote branch
+"
+	local current_branch
+
+	# Parse arguments
+	parse_args "$@"
+
+	! empty "$VERSION" || die "No version passed."
+
+	# Sanity checks
+	require_branch "$BRANCH"
+
+	BASE_BRANCH=$(flow_get_branch_base $BRANCH)
+	BASE_BRANCH=${BASE_BRANCH:-$DEVELOP_BRANCH}
+
+	current_branch=$(git stats --long-current-branch)
+	# We can't delete a branch we are on, switch to the develop branch.
+	if equals "$BRANCH" "$current_branch"; then
+		require_clean_working_tree
+		if git_local_branch_exists "$BASE_BRANCH"; then
+			git_checkout "$BASE_BRANCH"
+		else
+			git_checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
+		fi
+	fi
+
+	if ( git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH" && git_is_branch_merged_into "$BRANCH" "$BASE_BRANCH" ); then
+		git branch -d "$BRANCH" || die "Could not delete the $BRANCH."
+		if flag remote; then
+			git push "$ORIGIN" :"$BRANCH" || die "Could not delete the remote $BRANCH in $ORIGIN."
+		fi
+	else
+		die "Release branch '$BRANCH' has been not been merged in branch '$MASTER_BRANCH' and/or branch '$BASE_BRANCH'."
+	fi
+
+	flow_remove_branch_section "$BRANCH"
+
+	note "- Release branch '$BRANCH' has been deleted."
+	flag remote && note "- Release branch '$BRANCH' in '$ORIGIN' has been deleted."
+	note "- You are now on branch '$(git stats --long-current-branch)'"
 }
