[flow] some feature commands

diff --git a/bin/git-common b/bin/git-common
--- a/bin/git-common
+++ b/bin/git-common
@@ -12,7 +12,8 @@ git_set(){
   git config --file $(git stats --root-path)/.git/gadgets $(parse_before_config $1) "$2";
 }
 git_unset(){ git config --unset --file $(git stats --root-path)/.git/gadgets $(parse_before_config $1); }
-git_unset_all(){ git config --unset-all $(git stats --root-path)/.git/gadgets $(parse_before_config $1);}
+git_unset_all(){ git config --unset-all --file $(git stats --root-path)/.git/gadgets $(parse_before_config $1);}
+git_remove_section(){ git config --file $(git stats --root-path)/.git/gadgets --remove-section $(parse_before_config $1); }
 
 gadgets_is_initialized(){
   git rev-parse --git-dir >/dev/null 2>&1 && $(git_get core.master >/dev/null 2>&1)
@@ -141,6 +142,19 @@ git_branchs_with_prefix(){
 
 git_is_empty_repo(){
   [ $(find .git/objects -type f -print -quit | wc -c) -eq 0 ]
+}
+
+git_is_clean_working_tree() {
+	git rev-parse --verify HEAD >/dev/null || exit 1
+	git update-index -q --ignore-submodules --refresh
+
+	# Check for unstaged changes
+	git diff-files --quiet --ignore-submodules || return 1
+
+	# Check for Uncommited changes
+	git diff-index --cached --quiet --ignore-submodules HEAD -- || return 2
+
+	return 0
 }
 
 git_checkout(){
@@ -356,7 +370,14 @@ require_remote_branch_absent(){
 }
 
 require_branch_absent(){
-  ! git_branch_exists "$1" || die "Bbranch $1 exist. Choose another."
+  ! git_branch_exists "$1" || die "Branch $1 exist. Choose another."
+}
+
+require_branch_prefix(){
+  local branch prefix
+  branch="$1"
+  prefix="$2"
+  startswith "$branch" "$prefix" || die "$branch can't be used. NOt prefixed with $prefix."
 }
 
 require_branches_equal() {
@@ -377,5 +398,18 @@ require_branches_equal() {
 		else
 			die "Branches need merging first."
 		fi
+	fi
+}
+
+require_clean_working_tree() {
+	local result
+
+	git_is_clean_working_tree
+	result=$?
+	if [ $result -eq 1 ]; then
+		die "Working tree contains unstaged changes. Aborting."
+	fi
+	if [ $result -eq 2 ]; then
+		die "Index contains uncommited changes. Aborting."
 	fi
 }
diff --git a/bin/git-flow-feature b/bin/git-flow-feature
--- a/bin/git-flow-feature
+++ b/bin/git-flow-feature
@@ -4,9 +4,16 @@ SUBDIRECTORY_OK="yes"
 
 source $(git stats --script-location $0)/git-common
 
-loading(){
-  git_get flow.prefix.feature >/dev/null 2>&1 || die "Flow is not using feature branches. Use 'git flow init -f' to reconfigure."
-  prefix=$(git_get flow.prefix.feature)
+git_get flow.prefix.feature >/dev/null 2>&1 || die "Flow is not using feature branches. Use 'git flow init -f' to reconfigure."
+prefix=$(git_get flow.prefix.feature)
+
+parse_args(){
+  if empty "$1"; then
+    die "No branch candidate name passed."
+  else
+    candidate="$1"
+  fi
+  candidate_branch="$prefix$candidate"
 }
 
 list(){
@@ -47,7 +54,6 @@ list(){
 }
 
 start(){
-  local base candidate candidate_branch
   for arg do
     shift
     case "$arg" in
@@ -55,15 +61,11 @@ start(){
       *) set -- "$@" "$arg"; ;;
     esac
   done
-
-
-  ! empty "$1" || die "No branch candidate name passed."
-  candidate=$1
+  parse_args "$@"
   base=${2:-$DEVELOP_BRANCH}
-  candidate_branch=$prefix$candidate
 
   require_local_branch "$base"
-  flow_set_branch $candidate_branch $base
+  flow_set_branch_base $candidate_branch $base
 
   if flag fetch; then
     git_fetch_branch "$ORIGIN" "$base"
@@ -74,20 +76,155 @@ start(){
   if git_remote_branch_exists "$ORIGIN/$base"; then
     require_branches_equal "$base" "$ORIGIN/$base"
   fi
-  
+
   git_checkout $candidate_branch $base;
   note "Branch $candidate_branch created, based on $base."
   note "You are in branch $(git stats --long-current-branch)"
 }
 
 finish(){
-  BRANCH=${1:-`git stats --current-branch`}
-  git_checkout $DEVELOP_BRANCH && git merge --no-ff $prefix$BRANCH && git_checkout $DEVELOP_BRANCH$BRANCH;
+  for arg do
+    shift
+    case "$arg" in
+      --fetch) set_flag fetch; ;;
+      --rebase) set_flag rebase; ;;
+      --keep) set_flag keep; ;;
+      *) set -- "$@" "$arg"; ;;
+    esac
+  done
+  parse_args "$@"
+  if empty "$candidate"; then
+    candidate=$(git stats --long-current-branch)
+    candidate_branch=$prefix$candidate
+  fi
+  require_branch_prefix "$candidate_branch" "$prefix"
+  require_branch "$candidate_branch"
+  base=$(flow_get_branch_base "$candidate_branch")
+  base=${base:-$DEVELOP_BRANCH}
+  require_local_branch "$base"
+
+  # Sanity checks
+	require_clean_working_tree
+
+  # We always fetch the Branch from Origin
+	# This is done to avoid possible commits on the remote that are not
+	# merged into the local branch
+	if git_remote_branch_exists "$ORIGIN/$candidate_branch"; then
+		git_fetch_branch "$ORIGIN" "$candidate_branch"
+	fi
+
+  # Update local branches with remote branches
+	if flag fetch; then
+		git_fetch_branch "$ORIGIN" "$base"
+	fi
+
+  # Check if the local branches have all the commits from the remote branches
+	if git_remote_branch_exists "$ORIGIN/$candidate_branch"; then
+			require_branches_equal "$candidate_branch" "$ORIGIN/$candidate_branch"
+	fi
+	if git_remote_branch_exists "$ORIGIN/$base"; then
+		require_branches_equal "$base" "$ORIGIN/$base"
+	fi
+
+  # If the user wants to rebase, do that first
+	if flag rebase; then
+		if ! git flow feature rebase "$candidate"; then
+			warn "Finish was aborted due to conflicts during rebase."
+			warn "Please finish the rebase manually now."
+			warn "When finished, re-run:"
+			warn "    git flow feature finish '$candidate' '$base'"
+			exit 1
+		fi
+	fi
+
+  # Merge into BASE
+	git_checkout "$base" || die "Could not check out branch '$BASE_BRANCH'."
+  if [ "$(git rev-list -n2 "$base..$candidate_branch" | wc -l)" -eq 1 ]; then
+				git_do merge --ff "$candidate_branch"
+	else
+				git_do merge --no-ff "$candidate_branch"
+  fi
+
+  if [ $? -ne 0 ]; then
+    warn -f "We detected a merge conflict"
+    warn -f "Use 'git mergetool' and 'git commit' before try again. "
+    exit 1
+  fi
+
+  flow_unset_branch_base "$candidate_branch"
+  cleanup
+
 }
 
-push(){
-  BRANCH=${1:-`git stats --current-branch`}
-  git_checkout $DEVELOP_BRANCH && git push origin $DEVELOP_BRANCH && git branch -d $DEVELOP_BRANCH$BRANCH;
+cleanup(){
+  require_branch "$candidate_branch"
+  require_clean_working_tree
+
+  if ! flag keep; then
+    if git_remote_branch_exists "$ORIGIN/$candidate_branch"; then
+      git_remote_branch_delete "$candidate_branch"
+    fi
+
+    if equals "$candidate_branch" "$(git stats --long-current-branch)"; then
+      git_checkout "$base" || die "Could not checkout $base."
+    fi
+
+    git branch -d "$candidate_branch"
+    flow_remove_branch_section "$candidate_branch"
+  fi
+
+  if flag push; then
+    git push "$ORIGIN" "$base" || die "Could not push changes from $base to $ORIGIN."
+  fi
 }
 
-loading
+rebase() {
+
+	# Define flags
+	DEFINE_boolean 'interactive' false 'do an interactive rebase' i
+	DEFINE_boolean 'preserve-merges' false 'try to recreate merges' p
+
+  for arg do
+    shift
+    case "$arg" in
+      -i) set_flag interactive; ;;
+      --preserve-merges) set_flag preserve; ;;
+      *) set -- "$@" "$arg"; ;;
+    esac
+  done
+	# Parse arguments
+	parse_args "$@"
+
+	if empty "$candidate"; then
+    candidate=$(git stats --long-current-branch)
+    candidate_branch=$prefix$candidate
+  fi
+  require_branch_prefix "$candidate_branch" "$prefix"
+  require_branch "$candidate_branch"
+  base=$(flow_get_branch_base "$candidate_branch")
+  base=${base:-$DEVELOP_BRANCH}
+  require_local_branch "$base"
+
+	require_clean_working_tree
+
+	git_checkout "$candidate_branch"  || die "Could not check out branch $candidate_branch."
+	if flag interactive; then
+		opts="$opts -i"
+	fi
+	if flag preserve; then
+		opts="$opts -p"
+	fi
+	git rebase $opts "$base"
+}
+
+avoid_accidental_cross_branch_action() {
+	local current_branch
+
+	current_branch=$(git_current_branch)
+	if [ "$BRANCH" != "$current_branch" ]; then
+		warn "Trying to pull from '$BRANCH' while currently on branch '$current_branch'."
+		warn "To avoid unintended merges, git-flow aborted."
+		return 1
+	fi
+	return 0
+}
